### ISSUE TITLE
I am very confused and unable to use Ollama

### ISSUE THREAD

**Issue by Harry989** [rapmd73/Companion#1]
Hey there! I am loving the look of this project! It seems very interesting and I really wanna play around with it. Only issue I have is that I am seemingly incapable of getting ollama to generate messages. Mostly because I have no idea what I am supposed to do in order for it to work to begin with.

**Comment by rapmd73** [comment]
Hi, 

Let's start with the basics of Ollama itself.  Do you have a working local server? 

I will need to know more information about you VPS and what isn't working before I can really guide you to a working version of Companion. 

For example, are you having issues with Ollama not providing responses from the command line, or is it more specific to Discord? 

Thank you.

**Comment by Harry989** [comment]
I do have a functional Ollama installation, yes. And the API has been used by different applications in the past, so I know that definitely works too.

**Comment by rapmd73** [comment]
Please do a complete redownload and installation over. 

I have made several major bug fixes. 

Also, Are you running Companion on the system that is running Ollama? 

Thank you.

**Comment by MarshallYTHD** [comment]
I've followed the guide provided and it doesn't work. I'm able to run the ./LaunchCompanion and it starts the bot, and recognizes me sending messages, but doesn't reply to anything. It also didn't create a Logs folder.

**Comment by rapmd73** [comment]
Please make sure you are **root** when installing the program. 

Please update to the latest version as many significant bugs have been found that address the non-responsiveness of Companion. 

If you have any issues, please let me know. 

Thank you.
