### ISSUE TITLE
Log directory creation error. 

### ISSUE THREAD

**Issue by rapmd73** [rapmd73/Companion#2]
I've followed the guide provided and it doesn't work. I'm able to run the ./LaunchCompanion and it starts the bot, and recognizes me sending messages, but doesn't reply to anything. It also didn't create a Logs folder.

_Originally posted by @Marshall2HD in https://github.com/rapmd73/Companion/issues/1#issuecomment-2238823187_

**Comment by rapmd73** [comment]
Thank you for bringing this to my attention. This sounds like a bug in the installation. I'll investigate. 

Which AI engine are you using? Ollama or OpenAI? 

Thank you.

**Comment by Marshall2HD** [comment]
I’ve tried both OpenAI and Ollama. Neither worked.

**Comment by rapmd73** [comment]
Thank you for letting me know. This gives me a direction to look.

**Comment by rapmd73** [comment]
After abusing my system extensively, the only ways I've been able to reproduce this error is to try to install and run the program as non-root. 

Please be aware that you **MUST** be *root* for the program to install and run properly. This also includes installing it in the root contab for system startup. 

There have been other significant bugs fixed in the process of testing for this situation. Please be sure to update to the latest version as a few bugs that resulted in the system not responding were fixed. 

If you have any other issues or is this issue occurs again, please let me know. 

Thank you.
